import Head from "next/head";
import { useState, useEffect } from "react";
import { Box, Text, AspectRatio, useMediaQuery } from "@chakra-ui/react";

import Episode from "../components/Episode";

export default function Home() {
  const [isLargerThan855, setIsLargerThan855] = useState(true);
  const [mediaQuery] = useMediaQuery("(min-width: 836px)");
  console.log(isLargerThan855);

  useEffect(() => {
    if (mediaQuery !== isLargerThan855) {
      setIsLargerThan855(mediaQuery);
    }
  }, [mediaQuery]);
  return (
    <Box
      style={{ margin: 0, boxSizing: "borderBox", padding: 0 }}
      w="100vw"
      h="100vh"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AspectRatio as="header" minW="100vw" ratio={5 / 1}>
        <Box bgImage="/jamstack-bg.svg" bgRepeat="no-repeat" bgSize="cover">
          <Text
            color="white"
            fontFamily="Lobster"
            fontSize={isLargerThan855 ? "3rem" : "1.5rem"}
          >
            JamstackConf x Learn with Jason
          </Text>
        </Box>
      </AspectRatio>

      <Box
        as="main"
        w="100vw"
        bgColor="#111E51"
        display="flex"
        justifyContent="center"
      >
        <Box w="80%" h="100%" display="flex" flexDir="column">
          <Episode
            title="Custom Cart With Shopify Storefront API"
            src="https://www.youtube.com/embed/FJOJmKFngLI"
            isLargerThan855={isLargerThan855}
          />
          <Episode
            title="Custom Discount Codes With Fauna, Tito, and Shopify"
            src="https://www.youtube.com/embed/Iu87j6Mxfvw"
            isLargerThan855={isLargerThan855}
          />
          <Episode
            title="Custom Command Bar Using Autocomplete With Algolia"
            src="https://www.youtube.com/embed/_EY1yy4Whes"
            isLargerThan855={isLargerThan855}
          />
          <Episode
            title="Send Transactional Emails With Twilio SendGrid"
            src="https://www.youtube.com/embed/EYdvyc4xz24"
            isLargerThan855={isLargerThan855}
          />
          <Episode
            title="Monitor Errors and Performance With Sentry"
            src="https://www.youtube.com/embed/iP6RAlqJDvU"
            isLargerThan855={isLargerThan855}
          />
        </Box>
      </Box>
    </Box>
  );
}
